### ISSUE TITLE
PostgresSQL doc contains erroneous reference to MySQL

### ISSUE THREAD

**Issue by jamespfennell** [multiprocessio/datastation-documentation#20]
The SSH Proxy [Optional] section on [this page](https://github.com/multiprocessio/datastation-documentation/blob/6e6e54607cde672b29513c49040073e9b0484c9f/tutorials/Query_PostgreSQL_with_DataStation.md) begins with "If you want connect to a MySQL database..." whereas it should say PostgresSQL database presumably.

I would propose a change but I don't want to risk you getting entangled in my employer's annoying open source contribution policy...

**Comment by eatonphil** [comment]
Fixed, thank you!
