### ISSUE TITLE
Tutorial Links Broken

### ISSUE THREAD

**Issue by TechplexEngineer** [multiprocessio/datastation-documentation#21]
Tutorial Links from this page seem to be broken:
https://datastation.multiprocess.io/docs/latest/Panels/Database_Panels.html#postgresql

https://datastation.multiprocess.io/docs/latest/tutorials/Query_Elasticsearch_with_DataStation.html

**Comment by eatonphil** [comment]
Thank you! It's fixed now in [e57c4a5](https://github.com/multiprocessio/datastation-documentation/commit/e57c4a55e16e6ad3d9cd479e5d1df2a1dd429720)
